### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by shreyventure** [shreyventure/shopping-list#14]
Create an about page.

**Comment by vaibav03** [comment]
can I take up this issue?

**Comment by shreyventure** [comment]
> can I take up this issue?

Sure @vaibav03 .

The about page needs,
1. Heading ("About")
2. Paragraph (Fill it with [lorem ipsum](https://www.lipsum.com/feed/html) for now)

Create a `About.js` file in [client](https://github.com/shreyventure/shopping-list/tree/master/client)/[src](https://github.com/shreyventure/shopping-list/tree/master/client/src)/[Pages](https://github.com/shreyventure/shopping-list/tree/master/client/src/Pages)/ folder and Integrate it  as a router in [App.js](https://github.com/shreyventure/shopping-list/blob/master/client/src/App.js)
